"Name: \PR:SAPMV45A\FO:USEREXIT_SAVE_DOCUMENT_PREPARE\SE:END\EI
ENHANCEMENT 0 ZSD_ENH_MV45AFZZ_AUDAT_LOG.
IF vbak-audat GT '20260630'.
  MESSAGE 'Date can not be entered greater than 30.06.2026' TYPE 'E'.
ENDIF.
ENDENHANCEMENT.
